name: Deploy outlier datasets
on: [push]

jobs:
  build_bundle:
    name: Build data bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Build data bundles
        run: |
          mkdir bundles
          CB_RESULT_DIR=easy CB_RANDOM_STATE=123 CB_DIFFICULTY=simplest python create_bundle.py
          zip bundles/easy.zip -r --junk-paths easy/
          sha1sum bundles/easy.zip | cut -d " " -f 1 > bundles/easy.sha1
          CB_RESULT_DIR=hard CB_RANDOM_STATE=123 CB_DIFFICULTY=hardest python create_bundle.py
          zip bundles/hard.zip -r --junk-paths hard/
          sha1sum bundles/hard.zip | cut -d " " -f 1 > bundles/hard.sha1

      - uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: bundles/*

  deploy_bundle:
    name: Deploy data bundle
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/outlier-v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundles
          path: bundles

      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: alexellis/upload-assets@0.2.2
        name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./bundles/*"]'
