name: Deploy JSON repository
on:
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"

jobs:
  build_repo_json:
    name: Deploy repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Move files
        run: |
          mkdir repo
          mv repo.json repo/

      - name: Deploy repository JSON-file
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          destination_dir: ${{ github.ref_name }}
